### PR TITLE
Allow to specify more configuration to ZAP (certificates and configurations)

### PR DESCRIPTION
**Pull request by bhecquet**
This PR aims at giving user more control about ZAP options when it's started.
Specifically, it will be possible to:
- load HTTPS certificate (certload option), providing the certificate file
- define any additionnal configuration through the "-config" flag. For example, it will be posible to tell ZAP use a corporate proxy `-config connection.proxyChain.hostName=my.company.com -config connection.proxyChain.port=8080`

The 'startZap' step has been updated accordingly with new options 'rootCaFile' and 'additionalConfigurations'

- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x ] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by shardy-lbar** [comment]
Please manually rebase and resolve the conflicts.

**Comment by shardy-lbar** [comment]
@bhecquet there are still conflicts that need to be manually fixed.

**Comment by bhecquet** [comment]
Hello,

I looked at my commit and the code from master, I could not find the conflicts, could you point me their location please ?

Thanks

**Comment by shardy-lbar** [comment]
> Hello,
> 
> I looked at my commit and the code from master, I could not find the conflicts, could you point me their location please ?
> 
> Thanks

My bad, github was complaining about the commit history, not file conflicts (which I can resolve by using a squash rather than rebase merge). I'll review it and give it a test on our jenkins as soon as I am able.

**Pull request merged**
